name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:rr)

variables:
  RepoName: {your-repo-name}
  FolderPath: Templates/StorageAccount #change it you didn't follow our suggested path
  ArtifactName: storageAccount

resources:
  repositories:
    - repository: main
      type: git
      name: '$(RepoName)'

trigger: #continuous integration will be enabled for all branches and the path containing the ARM templates related to Storage Account
  branches:
    include:
      - '*'
  paths:
    include:
      - Templates/StorageAccount #change it you didn't follow our suggested path

stages:
- stage: build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-16.04
    workspace:
      clean: all
    
    steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Template Files as Azure DevOps artifact'
      inputs:
        PathtoPublish: $(FolderPath)
        ArtifactName: $(ArtifactName)